core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('showroomapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showroomapp/urls.py
from django.urls import path
from . import views

# app_name="showroomapp"

urlpatterns = [
    path('', views.home, name='home'),
    path('brand/<int:brand_id>/', views.brand, name='brand'),
    path('team/', views.team, name='team'),
]

showroomapp/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
fs = FileSystemStorage(location=settings.MEDIA_ROOT)
# Create your models here.

class ShowRoom(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Staff(models.Model):
    name = models.CharField(max_length=100)
    picture = models.ImageField(null=True, blank=True)
    position = models.CharField(max_length=100)
    showroom = models.ForeignKey(ShowRoom, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural="Staff"

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural="Brand"

    def __str__(self):
        return self.name

class Model(models.Model):
    name = models.CharField(max_length=100)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    engine = models.OneToOneField('Engine', on_delete=models.CASCADE)
    features = models.ManyToManyField('Feature')

    class Meta:
      verbose_name_plural="Model"

    def __str__(self):
        return self.name

class Engine(models.Model):
    engine_number = models.CharField(max_length=100, primary_key=True)
    name = models.CharField(max_length=100)
    specs = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural="Engine"

    def __str__(self):
        return self.name

class Feature(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural="Feature"

    def __str__(self):
        return self.name

class Car(models.Model):
    chassis_number = models.CharField(max_length=100, primary_key=True)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    stock = models.IntegerField(default=0)
    class Meta:
        verbose_name_plural="Car"

    def __str__(self):
        return self.chassis_number
 

showroomapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Brand, Staff

def home(request):
    brands = Brand.objects.all()
    return render(request, 'showroomapp/home.html', {'brands': brands})


def brand(request, brand_id):
    brand = get_object_or_404(Brand, id=brand_id)
    models = brand.model_set.all()
    return render(request, 'showroomapp/brand.html', {'brand': brand, 'models': models})


def team(request):
    staff_members = Staff.objects.all()
    return render(request, 'showroomapp/team.html', {'staff_members': staff_members})

showroomapp/templates/showroomapp/Team.html
{% extends 'showroomapp/base.html' %} 
  
 {% block title %} Team{% endblock %} 
  
 {% block content %} 
 <style> 
     img{ 
         width: 300px; 
         height: 300px; 
     } 
 </style> 
     <h1>Our Team</h1> 
     <ul> 
         {% for staff_member in staff_members %} 
             <li> 
                 Name: {{ staff_member.name }} <br> 
                 Position: {{ staff_member.position }} <br> 
                 Showroom: {{ staff_member.showroom }} <br> <br> 
                 {% if staff_member.picture %} 
                     <img src="{{ staff_member.picture.url }}" alt="{{ staff_member.name }}"> <br> <br> 
                 {% endif %} 
             </li> 
         {% endfor %} 
     </ul> 
 {% endblock %}

showroomapp/templates/showroomapp/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Car Showroom{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Car Showroom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'team' %}">Our Team</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

showroomapp/templates/showroomapp/brand.html
{% extends 'showroomapp/base.html' %}

{% block title %}
{{ brand.name }} Models{% endblock %}

{% block content %}
    <h1>{{ brand.name }} Models</h1>
    <ul>
        {% for model in models %}
            <li>
                <h2>{{ model.name }}</h2>
                <h3>Engine Specs:</h3>
                <p>{{ model.engine.specs }}</p>
                <h3>Features:</h3>
                <ul>
                    {% for feature in model.features.all %}
                        <li>{{ feature.name }}</li>
                    {% endfor %}
                </ul>
                <p>Stock Left: {{ model.car_set.first.stock|default:"0" }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

showroomapp/templates/showroomapp/home.html
{% extends 'showroomapp/base.html' %} 
  
 {% block title %} Brands{% endblock %} 
  
 {% block content %} 
     <h1>Car Showroom - Brands</h1> 
     <ul> 
         {% for brand in brands %} 
             <li><a href="{% url 'brand' brand.id %}">{{ brand.name }}</a></li> 
         {% endfor %} 
     </ul> 
 {% endblock %}